<!DOCTYPE html>
<html>
<head>
	<title>Contact</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="styleglobal.css">
</head>
<body>
	<h1>Contactez nous!</h1>
	<form action="contact.php" method="POST">
		<label>Pseudo:</label><p><input type="text" name="Pseudo"/></p>
		<label>Sujet:</label><p><input type="text" name="Sujet"/></p>
		<p><label>Entrer votre texte ici:</label><p><input type="text" name="information"></p></p>
		<input type="submit" value="Valider"/>
	</form>
</body>
</html>