<!DOCTYPE html>
<html>
	<head>
		<title>Revolution Library | Home</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="css/homecss.css">
		<script src="https://kit.fontawesome.com/f2574f15cd.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<div class="main_header">
		<header>
			<div class="logo_header_wrap">
				<a href="home.php"><img class="logo_header" src="./img/logo2.png"></a> 
				</div>
			<ol>
				
				<li><a href="home.phtml">Accueil</a></li>
				<li><a href="livres.php">Livres</a></li>
				<li><a href="client.php">Espace Client</a></li>
				<li><a href="contributeur.php">Espace Contributeur</a></li>
				<li><a href="formulaire_livre.php">Formulaire d'ajout</a></li>
				<li><a href="contact.phtml">Contactez nous</a></li>
			</ol>
		</header>
		</div>
		<br><br>
		
		<div class="main_part">
		<h2><i class="fas fa-map-pin"></i> Paris, France</h2>
		<h1>Revolution Library</h1>
		<p>La Librairie qui nourrit vos envies.</p>
		</div>

	</body>
</html>