<!DOCTYPE html>
<html>
<head>
	<title>Revolution Library | Livres</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="./css/styleglobal.css">
	<script src="https://kit.fontawesome.com/f2574f15cd.js" crossorigin="anonymous"></script>
</head>
<body class="body">
	<header>
				<div class="logo_header_wrap">
					<a href="home.php"><img class="logo_header" src="./img/logo2.png"></a> 
					</div>
				<ol>
					
					<li><a href="home.php">Accueil</a></li>
					<li><a href="livres.php">Livres</a></li>
					<li><a href="client.php">Espace Client</a></li>
					<li><a href="contributeur.php">Espace Contributeur</a></li>
				</ol>
			</header>
</body>
</html>